### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by hexonal** [caijianying/Service-invocation-monitor#8]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoSuchMethodError: net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.<init>([Lnet/bytebuddy/matcher/ElementMatcher;)V
	at com.caijy.agent.core.plugin.bytebuddy.AbstractJunction.and(AbstractJunction.java:12)
	at com.caijy.agent.core.plugin.PluginFinder.buildMatch(PluginFinder.java:60)
	at com.caijy.agent.TraceAgent.premain(TraceAgent.java:59)
	... 6 more

**Comment by hexonal** [comment]
pom 中增加
```xml
    <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
            <version>1.12.10</version>
        </dependency>
```
可以成功启动，但是依然存在报错
```
EXPRESS- 2024-06-12 14:18:00 [main] ERROR c.c.a.c.p.i.e.InstrumentMethodInterceptor [] - Service Invocation Monitor | before method invoke An Error occurred! from interceptor:MvcAnnotationInterceptor,reason:null
java.lang.NullPointerException: null
	at com.caijy.agent.plugin.mvc.annotation.MvcAnnotationInterceptor.getControllerURL(MvcAnnotationInterceptor.java:39)
	at com.caijy.agent.plugin.mvc.annotation.MvcAnnotationInterceptor.beforeMethod(MvcAnnotationInterceptor.java:23)
	at com.caijy.agent.core.plugin.interceptor.enhance.InstrumentMethodInterceptor.intercept(InstrumentMethodInterceptor.java:37)
	at com.tiki77.express.AtAppRun.springContextHolder(AtAppRun.java)
	at com.tiki77.express.AtAppRun$$EnhancerBySpringCGLIB$$1.CGLIB$springContextHolder$4(<generated>)
	at com.tiki77.express.AtAppRun$$EnhancerBySpringCGLIB$$1$$FastClassBySpringCGLIB$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.tiki77.express.AtAppRun$$EnhancerBySpringCGLIB$$1.springContextHolder(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:41002)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:42008)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
````

**Comment by caijianying** [comment]
是不是Controller上没有加@RequestMapping
